### ISSUE TITLE
Am I crazy or are the bulk downloads on the live site raw while these are clean?

### ISSUE THREAD

**Issue by palewire** [openelections/openelections-data-ia#4]

**Comment by dwillis** [comment]
They should be pretty similar, but the files on openelections.net have some things these files don't, like OCD identifiers.

**Comment by palewire** [comment]
I'm on an airplane about to land but I'm noticing some differences I can't quite explain. Probably just my ignorance. I will try to loop back later when I'm home and describe what I'm seeing more fully.
